# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruiseWeb', '0002_obtaineddataca'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
